export const CONSTANTS = {
  LANE_WIDTH: 4,
  GRAVITY: -40,
  JUMP_FORCE: 12,
  SNEAKER_JUMP_FORCE: 18,
  BASE_SPEED: 20,
  MAX_SPEED: 50,
  CHUNK_LENGTH: 60,
  PLAYER_Z: 0,
  JETPACK_HEIGHT: 10,
  MAGNET_RADIUS: 10,
  COIN_VALUE: 10,
};
